# Generated by Django 2.0 on 2021-12-17 07:01

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cylinder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cylinder_number', models.CharField(max_length=20)),
                ('assigned_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('state', django_fsm.FSMField(choices=[('with-retailer', 'with-retailer'), ('with-dispatch', 'with-dispatch'), ('with-user', 'with-user')], default='with-retailer', max_length=50, protected=True)),
            ],
        ),
    ]
